# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trussle
email: team@trussle.com
description: > # this means to ignore newlines until "baseurl:"
  See what you could afford in 60 seconds.
  Get a Mortgage in Principle in 5 minutes.
  Receive a mortgage recommendation within 24 hours.
  No fees!
# the subpath of your site, e.g. /blog
# IF YOU CHANGE THIS, CHANGE IT AT css/main.css
baseurl: "/blog"
url: "https://trussle.com" # the base hostname & protocol for your site
twitter_username: trussle

# Blog settings
permalink: ":slug"

# Build settings
markdown: kramdown

# Auto-generate sitemap.xml
gems:
  - jekyll-sitemap
